env_name: 'BipedalWalker-v3'
env_parameters:
  hardcore: true

agent_name: 
seed: 0 # Default seed if not provided
exp_name: part1_env02


run_id: ??? # decided during execution
test_num_episode: 30

#POLICY GRADIENT ACTOR CRITIC
pg_ac_train_episodes: 4000
pg_ac_gamma: 0.99
pg_ac_lr: 0.5e-2
pg_ac_batch_size: 256
pg_ac_buffer_size: 1e6

#DEEP DETERMINISTIC POLICY GRADIENT
ddpg_train_episodes: 8000
ddpg_gamma: 0.99
ddpg_lr: 1e-3
ddpg_tau: 0.005
ddpg_batch_size: 256
ddpg_buffer_size: 1e6



config_name: bipedalwalker_easy
testing: false
model_path: default

save_video: false
save_logging: true
save_model: true
use_wandb: true
silent: false

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
